[attachments]
source = fs
; capture = direct
repository = fs
driver = rsync

[attachments.source.fs]
path = /tmp/attachments-source

[attachments.capture.direct]

[attachments.repository.fs]
path = /tmp/attachments-repository

[attachments.driver.rsync]
archive = true
delete = true

[database]
source = fs
repository = fs
driver = rsync

[database.source.fs]
path = /tmp/database-source

[database.capture.direct]

[database.repository.fs]
path = /tmp/database-repository

[database.driver.rsync]
archive = true
delete = true
hardlinks = true
acl = true
xattrs = true
numeric_ids = true
